#  Pyrogram - Telegram MTProto API Client Library for Python
#  Copyright (C) 2017-present <https://github.com/TelegramPlayGround>
#
#  This file is part of Pyrogram.
#
#  Pyrogram is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published
#  by the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Pyrogram is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with Pyrogram.  If not, see <http://www.gnu.org/licenses/>.


from asyncio import sleep

import pyrogram
from pyrogram.raw.core import TLObject


class IterInvoke:
    async def iter_invoke(
        self: "pyrogram.Client",
        query: TLObject,
        key: str,
    ):
        """Invoke raw Telegram yield functions.

        This method makes it possible to do bakchodi.

        .. note::

            This is a utility method intended to be used **only** when working with raw
            :obj:`functions <pyrogram.api.functions>` (i.e: a Telegram API method you wish to use which is not
            available yet in the Client class as an easy-to-use method).

        .. include:: /_includes/usable-by/users-bots.rst

        Parameters:
            query (``RawFunction``):
                The API Schema function filled with proper arguments.

            key (``str``):
                The key using which to yield the iterator.

        Returns:
            ``Generator``: A generator yielding the raw type response object generated by the query.

        Raises:
            RPCError: In case of a Telegram RPC error.

        """

        r = await self.invoke(query)
        s = getattr(r, key, [])
        for d in s:
            await sleep(0)
            yield d
